# Generated by Django 4.2.7 on 2025-08-19 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Vertragsnummer"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monatlich"),
                            ("yearly", "Jaehrlich"),
                            ("nachhilfe", "Nachhilfe"),
                            ("trial", "Probestunden"),
                            ("custom", "Individuell"),
                        ],
                        max_length=10,
                        verbose_name="Vertragstyp",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("self", "Selbstzahler"),
                            ("sepa", "SEPA"),
                            ("jobcenter", "JobCenter"),
                            ("mixed", "Gemischt"),
                        ],
                        max_length=15,
                        verbose_name="Zahlungsart",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("active", "Aktiv"),
                            ("completed", "Abgeschlossen"),
                            ("cancelled", "Gekuendigt"),
                            ("suspended", "Ausgesetzt"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Startdatum")),
                ("end_date", models.DateField(verbose_name="Enddatum")),
                (
                    "cancellation_deadline",
                    models.DateField(verbose_name="Kuendigungsfrist"),
                ),
                (
                    "contract_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/",
                        verbose_name="Vertragsdatei",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
            ],
            options={
                "verbose_name": "Vertrag",
                "verbose_name_plural": "Vertraege",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("add_subject", "Fach hinzufuegen"),
                            ("remove_subject", "Fach entfernen"),
                            ("terminate_contract", "Vertrag kuendigen"),
                            ("new_contract", "Neuer Vertrag"),
                            ("change_schedule", "Stundenplan aendern"),
                            ("suspend_enrollment", "Anmeldung aussetzen"),
                        ],
                        max_length=20,
                        verbose_name="Antragstyp",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("processing", "In Bearbeitung"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "requested_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Gewuenschtes Startdatum"
                    ),
                ),
                (
                    "requested_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Gewuenschtes Enddatum"
                    ),
                ),
                (
                    "estimated_monthly_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Geschaetzte monatliche Aenderung",
                    ),
                ),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "parent_reason",
                    models.TextField(blank=True, verbose_name="Begruendung"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bearbeitet am"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin-Notizen"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Ablehnungsgrund"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Vertragsaenderungsantrag",
                "verbose_name_plural": "Vertragsaenderungsantraege",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Grundpreis"
                    ),
                ),
                ("price_date", models.DateField(verbose_name="Preisdatum")),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Endpreis"
                    ),
                ),
                (
                    "payer",
                    models.CharField(
                        choices=[("client", "Kunde"), ("jobcenter", "JobCenter")],
                        default="client",
                        max_length=15,
                        verbose_name="Zahler",
                    ),
                ),
                (
                    "hours_per_month",
                    models.IntegerField(default=4, verbose_name="Stunden pro Monat"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Vertragsposition",
                "verbose_name_plural": "Vertragspositionen",
            },
        ),
        migrations.CreateModel(
            name="ContractItemDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Rabattbetrag"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Angewandt am"
                    ),
                ),
            ],
            options={
                "verbose_name": "Angewandter Rabatt",
                "verbose_name_plural": "Angewandte Rabatte",
            },
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Urspruenglicher Betrag",
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Restbetrag"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Faelligkeitsdatum")),
                (
                    "overdue_since",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ueberfaellig seit"
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Zeitraum von")),
                ("period_end", models.DateField(verbose_name="Zeitraum bis")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Beglich"),
                ),
                (
                    "resolved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Beglichen am"
                    ),
                ),
                (
                    "late_fee_applied",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Mahngebuehren",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Schuld",
                "verbose_name_plural": "Schulden",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_description",
                    models.CharField(max_length=200, verbose_name="Bedingung"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Rabattwert"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Gueltig ab")),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="Gueltig bis"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "min_subjects",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Mindestanzahl Faecher"
                    ),
                ),
                (
                    "max_subjects",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hoechstanzahl Faecher"
                    ),
                ),
                (
                    "applies_to_family",
                    models.BooleanField(default=False, verbose_name="Familienrabatt"),
                ),
            ],
            options={
                "verbose_name": "Rabatt",
                "verbose_name_plural": "Rabatte",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="DiscountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "is_percentage",
                    models.BooleanField(default=True, verbose_name="Prozentual"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Rabatttyp",
                "verbose_name_plural": "Rabatttypen",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Rechnungsnummer"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(verbose_name="Abrechnungszeitraum von"),
                ),
                (
                    "period_end",
                    models.DateField(verbose_name="Abrechnungszeitraum bis"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Zwischensumme"
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Gesamtrabatt",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gesamtbetrag"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("sent", "Gesendet"),
                            ("paid", "Bezahlt"),
                            ("overdue", "Ueberfaellig"),
                            ("cancelled", "Storniert"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Rechnungsdatum")),
                ("due_date", models.DateField(verbose_name="Faelligkeitsdatum")),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Zahlungsdatum"
                    ),
                ),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="Rechnungsdatei",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
            ],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regelmaessiger Unterricht"),
                            ("individual", "Einzelunterricht"),
                            ("nachhilfe", "Nachhilfe"),
                            ("one_time", "Einmalige Gebuehr"),
                        ],
                        max_length=15,
                        verbose_name="Positionstyp",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Beschreibung"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Menge"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Einzelpreis"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Rabattbetrag",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Gesamtbetrag"
                    ),
                ),
                (
                    "payer",
                    models.CharField(
                        choices=[("client", "Kunde"), ("jobcenter", "JobCenter")],
                        max_length=15,
                        verbose_name="Zahler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnungsposition",
                "verbose_name_plural": "Rechnungspositionen",
            },
        ),
        migrations.CreateModel(
            name="OneTimeCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("library", "Bibliotheksgebuehr"),
                            ("costume", "Kostueme/Requisiten"),
                            ("materials", "Unterrichtsmaterialien"),
                            ("event", "Veranstaltung"),
                            ("registration", "Anmeldegebuehr"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=15,
                        verbose_name="Gebuehrentyp",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Beschreibung"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Betrag"
                    ),
                ),
                ("charge_date", models.DateField(verbose_name="Rechnungsdatum")),
                ("due_date", models.DateField(verbose_name="Faelligkeitsdatum")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Bezahlt")),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Zahlungsdatum"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
            ],
            options={
                "verbose_name": "Einmalige Gebuehr",
                "verbose_name_plural": "Einmalige Gebuehren",
                "ordering": ["-charge_date"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Betrag"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Bar"),
                            ("bank_transfer", "Ueberweisung"),
                            ("sepa", "SEPA-Lastschrift"),
                            ("card", "Kartenzahlung"),
                            ("jobcenter", "JobCenter"),
                        ],
                        max_length=15,
                        verbose_name="Zahlungsmethode",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("completed", "Abgeschlossen"),
                            ("failed", "Fehlgeschlagen"),
                            ("refunded", "Erstattet"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Zahlungsdatum")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Referenznummer"
                    ),
                ),
                (
                    "bank_details",
                    models.TextField(blank=True, verbose_name="Bankdaten"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
            ],
            options={
                "verbose_name": "Zahlung",
                "verbose_name_plural": "Zahlungen",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gesamtbetrag"
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Monatliche Rate"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Startdatum")),
                ("end_date", models.DateField(verbose_name="Enddatum")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
            ],
            options={
                "verbose_name": "Ratenzahlungsplan",
                "verbose_name_plural": "Ratenzahlungsplaene",
            },
        ),
        migrations.CreateModel(
            name="PaymentPlanInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.IntegerField(verbose_name="Ratennummer")),
                ("due_date", models.DateField(verbose_name="Faelligkeitsdatum")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Betrag"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Bezahlt")),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Zahlungsdatum"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Bezahlter Betrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate",
                "verbose_name_plural": "Raten",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preis pro Stunde"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Gueltig ab")),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="Gueltig bis"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preisliste",
                "verbose_name_plural": "Preislisten",
                "ordering": ["-valid_from"],
            },
        ),
    ]
