# Generated by Django 4.2.7 on 2025-08-19 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("parent", "Elternteil"),
                            ("child", "Kind"),
                            ("teacher", "Lehrer"),
                            ("admin", "Administrator"),
                            ("accountant", "Buchhalter"),
                        ],
                        max_length=15,
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geburtsdatum"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(blank=True, max_length=11, verbose_name="BIC"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bankname"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Spezialisierung"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Einstellungsdatum"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzerprofil",
                "verbose_name_plural": "Benutzerprofile",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Geburtsdatum")),
                (
                    "school_class",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Schulklasse"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "medical_notes",
                    models.TextField(blank=True, verbose_name="Medizinische Hinweise"),
                ),
                (
                    "special_needs",
                    models.TextField(blank=True, verbose_name="Besondere Beduerfnisse"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Elternteil",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kind",
                "verbose_name_plural": "Kinder",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
    ]
