# Generated by Django 4.2.7 on 2025-08-19 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("contract_change", "Vertragsaenderung"),
                            ("price_change", "Preisaenderung"),
                            ("schedule_change", "Stundenplanaenderung"),
                            ("discount_change", "Rabattaenderung"),
                            ("sepa_important", "SEPA Wichtig"),
                            ("absence_alert", "Fehlzeiten-Benachrichtigung"),
                            ("payment_reminder", "Zahlungserinnerung"),
                            ("request_status", "Antragsstatus"),
                            ("general", "Allgemeine Mitteilung"),
                        ],
                        max_length=20,
                        verbose_name="Benachrichtigungstyp",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niedrig"),
                            ("normal", "Normal"),
                            ("high", "Hoch"),
                            ("critical", "Kritisch"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioritaet",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("message", models.TextField(verbose_name="Nachricht")),
                ("is_read", models.BooleanField(default=False, verbose_name="Gelesen")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Wichtig"),
                ),
                (
                    "requires_acknowledgment",
                    models.BooleanField(
                        default=False, verbose_name="Bestaetigung erforderlich"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bestaetigt am"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelesen am"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Empfaenger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benachrichtigung",
                "verbose_name_plural": "Benachrichtigungen",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="notificatio_priorit_bf8ea0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(max_length=50, verbose_name="Tabellenname"),
                ),
                ("record_id", models.IntegerField(verbose_name="Datensatz-ID")),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="Feldname"),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, null=True, verbose_name="Alter Wert"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="Neuer Wert"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Geaendert am"
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(blank=True, verbose_name="Aenderungsgrund"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geaendert von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aenderungsprotokoll",
                "verbose_name_plural": "Aenderungsprotokolle",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="notificatio_table_n_e3d8ac_idx",
                    ),
                    models.Index(
                        fields=["changed_by"], name="notificatio_changed_7b540a_idx"
                    ),
                ],
            },
        ),
    ]
